language: java
jdk:
  - oraclejdk8
before_install:
  - pushd .
  - cd $HOME && git clone --depth=50 --branch=master https://github.com/yishnish/mytelnet.git && cd mytelnet && mvn install
  - cd $HOME && git clone --depth=50 --branch=master https://github.com/yishnish/nethack-screen-interpreter.git && cd nethack-screen-interpreter && mvn install
  - popd
after_success:
  - bash <(curl -s https://codecov.io/bash)